sudo: false
dist: trusty
language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk7
    - os: osx

addons:
  apt:
    packages:
      - ant-optional

before_install:
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi'

script:
  - ant gate
